apiVersion: v1
kind: Namespace
metadata:
  name: tanzu-system-ingress
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: contour-extension-sa
  namespace: tanzu-system-ingress
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: contour-extension-role
  namespace: tanzu-system-ingress
rules:
- apiGroups: [ "*" ]
  resources: [ "*" ]
  verbs: [ "*" ]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: contour-extension-rolebinding
  namespace: tanzu-system-ingress
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: contour-extension-role
subjects:
- kind: ServiceAccount
  name: contour-extension-sa
  namespace: tanzu-system-ingress
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: contour-extension-cluster-role
rules:
- apiGroups: [ "*" ]
  resources: [ "clusterroles", "clusterrolebindings", "customresourcedefinitions" ]
  verbs: [ "*" ]
- apiGroups: [ "" ]
  resources: [ "namespaces" ]
  verbs: [ "list" ]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: contour-extension-cluster-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: contour-extension-cluster-role
subjects:
- kind: ServiceAccount
  name: contour-extension-sa
  namespace: tanzu-system-ingress
---
apiVersion: kappctrl.k14s.io/v1alpha1
kind: App
metadata:
  name: contour
  namespace: tanzu-system-ingress
  annotations:
    tmc.cloud.vmware.com/managed: "false"
spec:
  syncPeriod: 30s
  serviceAccountName: contour-extension-sa
  fetch:
  - image:
      url: projects.registry.vmware.com/tkg/tkg-extensions-templates:v1.3.1_vmware.1
  template:
  - ytt:
      ignoreUnknownComments: true
      paths:
      - tkg-extensions/common
      - tkg-extensions/ingress/contour
      inline:
        pathsFrom:
        - secretRef:
            name: contour-data-values
  deploy:
  - kapp:
      rawOptions:
      - --wait-timeout=5m
      - --diff-changes=true
      - --diff-mask=false
      inspect:
        rawOptions:
        - --tree=true
---
apiVersion: v1
kind: Secret
metadata:
  name: contour-data-values
  namespace: tanzu-system-ingress
stringData:
  values.yaml: |
    #@data/values
    #@overlay/match-child-defaults missing_ok=True
    ---
    infrastructure_provider: "vsphere"
    envoy:
      service:
        type: NodePort