kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane
  extraPortMappings:
  - containerPort: 80
    hostPort: 80
    listenAddress: "0.0.0.0"
  - containerPort: 443
    hostPort: 443
    listenAddress: "0.0.0.0"
  extraMounts:
  - containerPath: /etc/containerd/certs.d/sslip.io.crt
    hostPath: ./certs/ca.crt
  - containerPath: /etc/containerd/add-tls-containerd-config.sh
    hostPath: ./add-tls-containerd-config.sh
